rotki/docs

.vitepress/theme/style.css

Decided not to change the font to roboto, because it's not suitable for long text (it hurts eyes)

style: adjust color and button border radius

---

contribution-guides/vue-typescript-testing.md
package.json
pnpm-lock.yaml

Update vue contribution

---

.vitepress/config.mts
.vitepress/theme/style.css
index.md
requirement-and-installation/build-from-source.md

feat: rearrange build from source

---

contribution-guides/vue-typescript.md

docs: add defineExpose position at the end

---

requirement-and-installation/build-from-source.md

docs: remove instruction that is not valid anymore

---

.github/workflows/ci.yml

ci: enable workflow for bugfixes and develop branches

---

usage-guides/custom-price.md

docs: put 'manually defined price' information

---

usage-guides/importing-data.md

docs: add coingecko and defillama

---

usage-guides/importing-data.md

Revert "docs: add coingecko and defillama"

---

.vitepress/config.mts

https://discord.com/channels/657906918408585217/1080778280807956490/1300395367812042752

fix: wrong navigation link for some sections

---

.vitepress/config.mts
.vitepress/theme/style.css
LICENSE.md
contribution-guides/contribute-as-developer.md
contribution-guides/manual-testing.md
index.md
package.json
requirement-and-installation/build-from-source.md
requirement-and-installation/index.md
usage-guides/accessing-db-manually.md
usage-guides/accounts-and-balances.md
usage-guides/address-book.md
usage-guides/assets.md
usage-guides/backend-arguments.md
usage-guides/calendar.md
usage-guides/customization.md
usage-guides/data-directory.md
usage-guides/decentralized-finance.md
usage-guides/historical-events.md
usage-guides/importing-data.md
usage-guides/index.md
usage-guides/pnl.md
usage-guides/troubleshooting.md

docs: change rotki to lowercase

---

.vitepress/config.mts
faq.md
usage-guides/historical-events.md
usage-guides/troubleshooting.md

docs: list supported events in history events

---

usage-guides/importing-data.md

- Do not repeat yourself for many of the import options.
- Add missing ones
- Specify types of data imported per data source

Improve import docs

---

requirement-and-installation/packaged-binaries.md

Related to [rotki/rotki#2535](https://github.com/rotki/rotki/issues/2535)

docs: add watchtower service to /packaged-binaries.md docker section

---

package.json
pnpm-lock.yaml

chore: dependency updates

---

usage-guides/index.md

As per https://discord.com/channels/657906918408585217/745172610240872508/1314199304071806986

add a warning not to run multiple devices with Premium simultaneously

---

faq.md
usage-guides/index.md

docs: issue that needs global db move

---

contribution-guides/vue-typescript.md

fix: update information about husky hooks

---

.vitepress/config.mts
components/CsvTable.vue
components/csv-loader.data.ts
contribution-guides/contribute-as-developer.md
requirement-and-installation/build-from-source.md
requirement-and-installation/packaged-binaries.md
usage-guides/accounts-and-balances.md
usage-guides/customization.md
usage-guides/importing-data.md
usage-guides/index.md
usage-guides/pnl.md
usage-guides/staking.md
usage-guides/statistic.md

docs: update some outdated docs

---

faq.md

docs: information about lifetime premium plan

---

.vitepress/theme/index.ts
contribution-guides/contribute-as-developer.md
package.json
pnpm-lock.yaml
usage-guides/api-keys.md
usage-guides/customization.md

chore: update dependencies

---

usage-guides/customization.md

chore: Say snapshot
